---
author: "your_name"
title: "Prediction Based on Betting Markets"
date: "date"
output: 
    html_document: default
    pdf_document: default
---


Earlier in the chapter, we studied the prediction of election outcomes
using polls.  Here, we study the prediction of election outcomes based
on betting markets.  In particular, we analyze data for the 2008 and
2012 US presidential elections from the online betting company, called
Intrade.  At Intrade, people trade contracts such as 'Obama to win
the electoral votes of Florida.'  Each contract's market price
fluctuates based on its sales.  Why might we expect betting markets
like Intrade to accurately predict the outcomes of elections or of
other events?  Some argue that the market can aggregate available
information efficiently.  In this exercise, we will test this 
*efficient market hypothesis* by analyzing the market prices of
contracts for Democratic and Republican nominees' victories in each
state.

The data files for 2008 and 2012 are available in CSV format as
`intrade08.csv` and `intrade12.csv`, respectively. The variables in these datasets are:

--------------------------------------------------------------------------------
 Name                Description
 ------------------- ----------------------------------------------------------
 `day`               Date of the session 
 
 `statename`         Full name of each state (including District of 
                     Columbia in 2008) 
 
 `state`             Abbreviation of each state (including District of 
                     Columbia in 2008)
 
 `PriceD`            Closing price (predicted vote share) of Democratic 
                     Nominee's market
 
 `PriceR`            Closing price (predicted vote share) of Republican 
                     Nominee's market 
 
 `VolumeD`           Total session trades of Democratic Party Nominee's 
                     market
 
 `VolumeR`           Total session trades of Republican Party Nominee's 
                    market 
--------------------------------------------------------------------------------

Each row represents daily trading
information about the contracts for either the Democratic or
Republican Party nominee's victory in a particular state. 

We will also
use the election outcome data.  These data files are
`pres08.csv` and `pres12.csv` with variables:

--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ----------------------------------------------------------
 `state.name`         Full name of state (only in `pres2008`)
 
 `state`              Two letter state abbreviation
 
 `Obama`              Vote percentage for Obama
 
 `McCain`             Vote percentage for McCain
 
 `EV`                 Number of electoral college votes for this state
--------------------------------------------------------------------------------
 
We'll also use poll data from 2008 and 2012 in the files `polls08.csv` and `polls12.csv`,  The variables in the polling data are:
  
--------------------------------------------------------------------------------
 Name                 Description
 -------------------- ---------------------------------------------------------
 `state`              Abbreviated name of state in which poll was conducted 
 
 `Obama`              Predicted support for Obama (percentage)
 
 `Romney`             Predicted support for Romney (percentage) 
 
 `Pollster`           Name of organization conducting poll 
 
 `middate`            Middle of the period when poll was conducted 
--------------------------------------------------------------------------------

## Question 1

We will begin by using the market prices on the day before the
  election to predict the 2008 election outcome.  To do this, subset
  the data such that it contains the market information for each state
  and candidate only on the day before the election.  Note that in
  2008 the election day was November 4.  We compare the closing prices
  for the two candidates in a given state and classify a candidate
  whose contract has a higher price as the predicted winner of that
  state.  Which states were misclassified?  How does this compare to
  the classification by polls presented earlier in this chapter?
  Repeat the same analysis for the 2012 election, which was held on
  November 6.  How well did the prediction market do in 2012 compared
  to 2008?  Note that in 2012 some less competitive states have
  missing data on the day before the election because there were no
  trades on the Republican and Democratic betting markets. Assume
  Intrade predictions would have been accurate for these states.

## Question 2

How do the predictions based on the betting markets change over
  time?  Implement the same classification procedure as above on each
  of the last 90 days of the 2008 campaign rather than just the day
  before the election.  Plot the predicted number of electoral votes
  for the Democratic party nominee over this 90-day period.  The
  resulting plot should also indicate the actual election result.
  Note that in 2008, Obama won 365 electoral votes. Briefly comment on
  the plot.

## Question 3

Repeat the previous exercise but this time use the seven-day
  *moving-average* price, instead of the daily price, for each
  candidate within a state.  This can be done with a
  loop. For a given day, we take the average of the Session Close
  prices within the past seven days (including that day).  To answer
  this question, we must first compute the seven-day average within
  each state. Next, we sum the electoral votes for the states Obama is
  predicted to win.  Using the `tapply` function will allow us
  to efficiently compute the predicted winner for each state on a
  given day.
  
## Question 4

Create a similar plot for 2008 state-wide poll predictions using
  the data file `polls08.csv`. Notice that polls are not conducted daily
  within each state. Therefore, within a given state for each of the
  last 90 days of the campaign, we compute the average margin of
  victory from the most recent poll(s) conducted. If multiple polls
  occurred on the same day, average these polls. Based on the most
  recent predictions in each state, sum Obama's total number of
  predicted electoral votes. One strategy to answer this question is
  to program two loops - an inner loop with 51 iterations for each
  state and an outer loop with 90 iterations for each day.
  
## Question 5

What is the relationship between the price margins of the
  Intrade market and the actual margin of victory? Using only the
  market data from the day before the election in 2008, regress
  Obama's actual margin of victory in each state on Obama's price
  margin from the Intrade markets. Similarly, in a separate analysis,
  regress Obama's actual margin of victory on the Obama's predicted
  margin from the latest polls within each state. Interpret the
  results of these regressions.

## Question 6


Do the 2008 predictions of polls and Intrade accurately predict
  each state's 2012 elections results?  Using the fitted regressions
  from the previous question, forecast Obama's actual margin of
  victory for the 2012 election in two ways.  First, use the 2012
  Intrade price margins from the day before the election as the
  predictor in each state.  Recall that the 2012 Intrade data do not
  contain market prices for all states. Ignore states without data.
  Second, use the 2012 poll predicted margins from the latest polls in
  each state as the predictor, found in `polls12.csv`.

